### PR TITLE
service worker test

### PR DESCRIPTION
**Pull request by scruffian**

### CODE REVIEW

**Comment by KarenSingleton** [comment]
Hey Ben

Are you wanting a JavaScripture session sometime?

**Comment by scruffian** [comment]
Yes! I've made so many changes...

**Comment by KarenSingleton** [comment]
As a group or in spare time?

**Comment by scruffian** [comment]
Either? Both?

**Comment by KarenSingleton** [comment]
I’m better in a group. I’m useless doing stuff in my own time

**Pull request merged**
